version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./assets/mongo-dump:/mongo-dump
      - ./scripts/mongo-restore.sh:/docker-entrypoint-initdb.d/mongo-restore.sh

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

volumes:
  mongodb_data_container: